name: Scrapy CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 2 * * *"   # run every day at 02:00 UTC
  workflow_dispatch:

jobs:
  scrapy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create output folder
        run: mkdir -p output
        
      - name: Build Docker image
        run: docker build -t scrapy-bot .

      - name: Run spider
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/output:/app/output \
            scrapy-bot crawl my_spider \
            -o output/$(date +%Y_%m_%d)_output.json

